---
title: "Quiz 2 - February 9"
author:
  - name: Tom Hanna
    id: th
    orcid: 0000-0002-8054-0335
    email: tlhanna@central.uh.edu
    url: tomhanna.me
    affiliation:
      - name: University of Houston
        city: Houston
        state: TX
        url: uh.edu/class/political-science/
license: CC BY-NC-SA 4.0
copyright:
  holder: Tom Hanna
  year: 2026
date: today
format:
  html:
    theme: cosmo
    style: custom.css
    axe: true
    self-contained: true
    code-fold: false
    logo: ../logo.png
    footer: "POLS3312, Spring 2026, Instructor: Tom Hanna"
  revealjs:
    self-contained: true
    code-fold: true
    code-summary: "Show the code"
    transition: convex
    incremental: true
    theme: [default, ../custom.scss]
    logo: ../logo.png
    footer: "POLS3312, Spring 2026, Instructor: Tom Hanna"
  docx:
    toc: true
    number-sections: true
    reference-doc: ../../word-template.docx
  pdf:
    toc: true
    toc-depth: 2
    toc-location: left
    number-sections: true
    fig_caption: true
---

## Instructions

1. Please read each question carefully and answer to the best of your ability.
2. Write your name here: _____________________________
3. You may simplify to least common denominator and to the radical expression, $\sqrt{xxx}$, if necessary.


## Question 1

What is the median of the following set of numbers: 3, 7, 5, 9, 1?


## Question 2

What is the mean of the following set of numbers: 4, 8, 6, 10, 2?


## Question 3

What is the mode of the following set of numbers: 2, 4, 6, 4, 8, 2, 4?

## Question 4

What is the mode of the following set of numbers: 1, 2, 3, 4, 5, 6, 7, 8, 9?

## Question 5


What is the median of the following set of numbers: 10, 20, 30, 40, 50, 60?

## Question 6 

What is the mode of the following set of numbers: 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2?

## Question 7

What is the mean of the following set of numbers: 5, 10, 15, 20, 25?

## Question 8

What is the median of the following set of numbers: 5, 10, 15, 20, 25?

## Question 9

What is the mode of the following set of numbers: 5, 10, 15, 20, 25?


## Question 10

What is the standard deviation of x if the variance of x is 100?

## Question 11

What is the variance of x if the standard deviation of x is 5?

## Question 12

- If the sum of squared deviations from the mean is 1000 and the number of observations is 11, what is the sample variance? 

## Question 13

From the question above, what is the sample standard deviation?

